version: "3.8"
services:
  nodejs-app:
    container_name: nodejsapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10000:10000"
    environment:
      NODE_ENV: production
      PORT: 10000
