name: CICD

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }} 
      - name: Build docker image
        run: docker build -t jietung02/nodejs-app .
      - name: Publish image to docker hub
        run: docker push jietung02/nodejs-app:latest
        
  deploy:
    needs: build
    runs-on: [self-hosted]
    steps:
      - name: Pull image from docker hub
        run: docker pull jietung02/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run docker container
        run: docker run -p 8000:8000 --name nodejs-app-container jietung02/nodejs-app