name: CICD

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} 
      - name: Build docker image
        run: docker build --build-arg NODE_ENV=${{ secrets.NODE_ENV }} -t salonxpertbackend/nodejs-app .
      - name: Publish image to docker hub
        run: docker push salonxpertbackend/nodejs-app:latest
        
  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: docker pull salonxpertbackend/nodejs-app:latest
      - name: Delete old container
        run: docker rm -f nodejs-app-container
      - name: Run docker container
        run: docker run -d -p 10000:10000 --name nodejs-app-container salonxpertbackend/nodejs-app